### ISSUE TITLE
HTTP/3 explained front page

### ISSUE THREAD

**Issue by bagder** [bagder/http3-explained#1]
Anyone with some design skills want to take a stab at making a front page for this document?

- Size of 1800x2360 pixels for cover.jpg, 200x262 for cover_small.jpg
- No border
- Clearly visible book title
- Any important text should be visible in the small version

The official quic logo might be a good idea to use somehow:

![quic](https://user-images.githubusercontent.com/177011/37913246-b9fdd958-3114-11e8-8a04-ddf7e203e6b3.png)
![quic-wider](https://user-images.githubusercontent.com/177011/37913247-ba21471c-3114-11e8-80a2-e572bba4e981.png)

There is no official HTTP/3 logo. It might be amusing to use the "scary" 3 from Mike Bishop's IETF 103 presentation:

![http3](https://daniel.haxx.se/blog/wp-content/uploads/2018/10/Screenshot_2018-11-06-HTTP-QUIC-slides-103-httpbis-httpquic-00.png)

**Comment by bagder** [comment]
Here's another image that might be used, which I've created for inclusion in quic related presentations...

![lego-quic-man](https://user-images.githubusercontent.com/177011/38604183-e47e70a4-3d6f-11e8-9f3e-c3ef032c191c.jpg)

**Comment by drequivalent** [comment]
![bitmap](https://user-images.githubusercontent.com/1463277/49652712-e6660a80-fa43-11e8-98c6-77a791a47f38.png)
Hit me up if you need svg

**Comment by bagder** [comment]
I like it!

Even if it isn't exactly the rooster man I think it would make the "blueprint man" more relevant in the image if it has the quic logo on its chest in that style or something. Oh, and I'd appreciate my last name spelled as "Stenberg" without an 'i'... :grin:

**Comment by drequivalent** [comment]
Awkward

**Comment by bagder** [comment]
@drequivalent do want to turn this into a "final" image we can use? I don't see many other competing suggestions...

**Comment by bagder** [comment]
Given the time that has passed and that nobody stepped up so far to the entire job, I'm closing this issue.
