### ISSUE TITLE
German translation incomplete - SUMMARY.md missing

### ISSUE THREAD

**Issue by bastischubert** [bagder/http3-explained#118]
Hi there,

the german translation on https://http3-explained.haxx.se/de/ just has the Introduction, but is missing the other sections.
Seems like the SUMMARY.md is missing for the german translation (according to https://twitter.com/bagder/status/1151084419421265920)

**Comment by bagder** [comment]
@5k9m, I think you should add the SUMMARY.md with at least the pages that are already translated. Possibly you can also create blank (or English) ones if there are pieces still not translated as it will also show others where they can join in and help!

**Comment by 5k9m** [comment]
Thanks @bastischubert & @bagder!
I added SUMMARY.md and hope to finish the next section by this weekend.

**Comment by bagder** [comment]
Thanks @5k9m!
