### ISSUE TITLE
How is Websocket planned in HTTP/3

### ISSUE THREAD

**Issue by git001** [bagder/http3-explained#121]
There is a RFC for [Bootstrapping WebSockets with HTTP/2](https://tools.ietf.org/html/rfc8441) what's the plan for WS in HTTP/3?

**Comment by quantumsheep** [comment]
For now there is absolutely no information about a potential WebSockets implementation for QUIC. But it may end up being a WebSockets UDP extension with the use of the `Sec-Websocket-Extensions` header for instance.

It's actually being discussed a lot in the QUIC community, but the working group doesn't seem to have started discussions about it.

**Comment by git001** [comment]
@quantumsheep thank you

**Comment by lucsoft** [comment]
after 1 1/2 year are there some news? i love the idea to see websockets over udp

**Comment by bagder** [comment]
It seems "they" work on having "web transport" become the websocket replacement in the future: https://w3c.github.io/webtransport/ So no, no websockets for h3.

**Comment by onpaws** [comment]
Thanks for sharing that link @bagder -- _exactly_ the info I was hoping to find

**Comment by qm3ster** [comment]
WebSocket over real QUIC streams will be here sooner than you can possibly imagine: https://datatracker.ietf.org/doc/rfc9220/

**Comment by nikolaydimitrov** [comment]
So anyone knows what the current browser behaviour is?
If we already have HTTP3/QUICK connection it is "ignored" and a new HTTP1.1 (TCP) connection is open for the WebSocket?
