### ISSUE TITLE
Long sentence in [why-quic] section.

### ISSUE THREAD

**Issue by alishir** [bagder/http3-explained#186]
It seems the first sentence in the second paragraph is long and we could break it in to two separate sentence.
Here is the main sentence:

> QUIC is in many ways what could be seen as a way of doing a new reliable and
secure transport protocol that is suitable for a protocol like HTTP and that
can address some of the known shortcomings of doing HTTP/2 over TCP and
TLS.

**Comment by bagder** [comment]
Simplified:

> QUIC is a new reliable and secure transport protocol that is suitable for a
protocol like HTTP and that can address some of the known shortcomings of
doing HTTP/2 over TCP and TLS. The logical next step in the web transport
evolution.
