### ISSUE TITLE
QUIC is an acronym.

### ISSUE THREAD

**Issue by qifeng0748** [bagder/http3-explained#20]
/en/why-quic.md:
"QUIC is a name, not an acronym. "

QUIC is an acronym by Quick UDP Internet Connections.

> What is QUIC?
> 
> QUIC (Quick UDP Internet Connections) is a new transport protocol for the internet, developed by 
> Google.

In this [https://www.chromium.org/quic](https://www.chromium.org/quic) page. Documentation - [QUIC overview](https://docs.google.com/document/d/1gY9-YNDNAB1eip-RTPbqphgySwSNSDHLq9D5Bty4FSU/edit)

**Comment by yi-bai** [comment]
https://github.com/bagder/http3-explained/blob/master/en/proc.md
It's no longer true according to this.

**Comment by qifeng0748** [comment]
@yi-bai Thank you!

**Comment by bagder** [comment]
This fact is stated in the QUIC protocol drafts. See https://tools.ietf.org/html/draft-ietf-quic-transport-16#section-1.2
