### ISSUE TITLE
Change "HTTP over QUIC" to "HTTP/3"

### ISSUE THREAD

**Issue by OldBigBuddha** [bagder/http3-explained#25]
I think you should change `HTTP over QUIC` to `HTTP/3` in the documents.

[HTTP/3 | daniel.haxx.se](https://daniel.haxx.se/blog/2018/11/11/http-3/)

**Comment by bagder** [comment]
It is referred to as "HTTP/3" in most places already. Are there any specific places where you think we should update the current text?

**Comment by bagder** [comment]
It is on purpose as I speak of HTTP over QUIC in the generic sense there.

**Comment by OldBigBuddha** [comment]
Okay, I understand.
Thank you very much.
And I'll reflect this issue to the document of Japanese.
