### ISSUE TITLE
[ja] Remove extra spacing

### ISSUE THREAD

**Issue by momdo** [bagder/http3-explained#42]
Since markdown's line break in Japanese is interpreted as a space, I think that it is better to remove the line breaks...

For example (in [ja/criticism.md](https://raw.githubusercontent.com/bagder/http3-explained/master/ja/criticism.md)): 

> ポート53 (DNS に使われる) 以外の UDP トラフィックをブロックするか、あるいは
> 利用制限をかけています。

This is rendered in [HTML in this way](https://http3-explained.haxx.se/ja/criticism.html):
> ポート53 (DNS に使われる) 以外の UDP トラフィックをブロックするか、あるいは 利用制限をかけています。

It makes it more readable by modifying the md file as follows:
> ポート53 (DNS に使われる) 以外の UDP トラフィックをブロックするか、あるいは利用制限をかけています。

**Comment by inductor** [comment]
Should be fixed. Can you confirm?

**Comment by momdo** [comment]
Awesome! Thank you for your quick service :-)
