### ISSUE TITLE
regd. number of frame types

### ISSUE THREAD

**Issue by saravananmk** [bagder/http3-explained#52]
https://http3-explained.haxx.se/en/h3-streams.html

Original:
```
HTTP/3 frames

HTTP/3 means setting up QUIC streams and sending over a set of frames to the
other end. There's but a small fixed number (eight!) of known frames in HTTP/3. 
```
I was reading https://tools.ietf.org/html/draft-ietf-quic-http-17  It list 9 frames:

1) DATA
2) HEADERS
3) PRIORITY
4) CANCEL_PUSH
5) SETTINGS
6) PUSH_PROMISE
7) GOAWAY
8) MAX_PUSH_ID
9) DUPLICATE_PUSH

So may be you can change the "eight" into "nine"? Alternatively, you can remove "eight" altogether, just in case if they add/remove any frames in future drafts.

**Comment by bagder** [comment]
Fixed
