### ISSUE TITLE
Some confusing wording and my suggestions

### ISSUE THREAD

**Issue by yfdyh000** [bagder/http3-explained#63]
I have read this book recently, it is good, but a little wording seems to be confusing to the reader, so I sent my comments here for improvement.

1. `and there are never any unencrypted QUIC connections.` in feature-tls.html
This sounds a bit like there is no plaintext messages, even if it is a handshake message. I understand it is saying there is no leak of the transmitted data.

2. `official QUIC protocol` in proc-status.html
I understand the Google's QUIC protocol is proprietary, but it is popular and used, so the "official" is confusing, The used `The IETF QUIC protocol` may be better.

3. `Based on UDP it also then uses UDP port numbers to identify specific servers on a given machine.` in feature-udp.html
"specific servers on a given machine." is a less obvious concept, I used to think that it said "services", but it may also be saying that the servers is behind a NAT router. Maybe it can be said "identify specific servers behind a given address."?  Or it's my problem, I first think of the servers as a host rather than running server software behind a port.

4. `Version negotiation` in quic-connections.html
This mechanism seems similar to the TLS handshake, but as a general reader, I can't quite understand why and how to select the protocol version from the client.

5. `Back then, QUIC was still claimed to be an acronym for "Quick UDP Internet Connections", but that has been dropped since then.` in proc.html
I hope it provides a reference as it seems not easy to find.

6. feature-http.md and h3.md have the same subtitles, although they have different directorie (SUMMARY.md) titles.

7. In quic-connections.html, change the "wifi" to "Wi-Fi", "download" to "downloads"? I am not sure.

**Comment by bagder** [comment]
1. It means that all QUIC *connections* are encrypted and secure. There are no clear-text/plain-text versions like for TCP (and HTTP/1 and HTTP/2). As mentioned somewhere, there are one or a few unprotected *packets* in the early handshake, but this sentence speaks of *connections*.

**Comment by bagder** [comment]
2. Agred. Will update.

**Comment by bagder** [comment]
3. Services it is then. I checked and the wikipedia article on "port" says "network services".

New version:

> Based on UDP it also then uses UDP port numbers to identify specific network services on a given IP address.

**Comment by bagder** [comment]
4. A *user* would probably never select QUIC version, but there might still be implementations that implement multiple versions and thus can use one out of of several available.

I suppose that can be explained a bit better...

**Comment by yfdyh000** [comment]
> It means that all QUIC connections are encrypted and secure. There are no clear-text/plain-text versions like for TCP (and HTTP/1 and HTTP/2). As mentioned somewhere, there are one or a few unprotected packets in the early handshake, but this sentence speaks of connections.

I understand now, those UDP requests don't be *connections* (of QUIC) for establishing a QUIC connection, they are a kind of session packets instead of a connection.

>    A user would probably never select QUIC version, but there might still be implementations that implement multiple versions and thus can use one out of of several available.
>I suppose that can be explained a bit better...

As far as I am concerned, this sounds like explaining different things.

My confusion is, why the first request from the client is not belong to requesting the supported versions list (or similar), but instead "will tell the server which QUIC protocol version it wants to speak", then "the client to select" again. Does this design have any deep meaning, or the "tells" just a handshake packet version field. It sounds like the server doesn't care about the “it wants to speak" from client.

**Comment by bagder** [comment]
> 5. I hope it provides a reference as it seems not easy to find.

[QUIC is a name, not an acronym](https://tools.ietf.org/html/draft-ietf-quic-transport-18#section-1.2)

**Comment by bagder** [comment]
> why the first request from the client is not belong to requesting the supported versions list

You're here asking why the protocol is defined to work as it is, and that's a question for the QUIC working group. This document explains exactly how it works and what is defined in the QUIC drafts. I actually have not seen the exact discussion that led up to this specific design. If you read the draft and think the current explanation isn't doing it justice, then please let us know.
