### ISSUE TITLE
why HTTP/3 at all?

### ISSUE THREAD

**Issue by robaho** [bagder/http3-explained#76]
It seems the only real benefit is the avoidance of HTTP stalls - but given all of the infrastructure limitations in existence - anything over UDP seems unlikely. As the author of a major system that used UDP to avoid some of the same TCP drawbacks, I can confirm that it is a struggle using UDP over the internet.

So, why not just use HTTP/2 and then open multiple connections and bond them. Seems it solves the major problem that QUIC is trying to solve.

**Comment by bagder** [comment]
That's not a question for this document though - we're not the QUIC working group. We document HTTP/3 and QUIC. If you want to design another protocol then I salute you and wish you good luck.

**Comment by robaho** [comment]
Fair enough. It’s a shame the working group doesn’t have a commenting section, at least that I could find.

**Comment by bagder** [comment]
It has a mailing list for questions and discussions. It has a github repo for issues and pull-requets against the specs.
